  query GetPosts {
    publication(host: "blog.nurulhudaapon.com") {
      isTeam
      title
      posts(first: 10) {
        edges {
          node {
            id
            coverImage {
              url
            }
            publishedAt
            readTimeInMinutes
            slug
            subtitle
            views
            title
            brief
            url
            author {
              name
            }
          }
        }
      }
    }
  }
  